# builder stage
FROM prosonit/vllm-builder-6-1:1.0 AS builder

# production image
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

RUN apt-get update && \
    apt-get install -y python3.10 python3-pip libaio-dev && \
    ln -sf /usr/bin/python3.10 /usr/bin/python && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# copy entire python install from builder
COPY --from=builder /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY --from=builder /usr/local/bin/vllm /usr/local/bin/vllm
COPY --from=builder /usr/local/bin/vllm-* /usr/local/bin/  # to catch all scripts
COPY --from=builder /etc/* /etc/  # only if you know what you need

ENV PATH="/usr/local/bin:$PATH"

# optionally set entrypoint
ENTRYPOINT ["vllm"]
CMD ["--help"]
