# builder stage
FROM prosonit/vllm-builder-6-1:2.0 AS builder

# production image
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

#RUN apt-get update && \
#    apt-get install -y python3.10 python3-pip libaio-dev && \
#    ln -sf /usr/bin/python3.10 /usr/bin/python && rm -rf /var/lib/apt/lists/*

#RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y python3 python3-pip libaio-dev libexpat1 && rm -rf /var/lib/apt/lists/*

# copy entire python install from builder
#COPY --from=builder /usr/local/lib/python3.10 /usr/local/lib/python3.10
#COPY --from=builder /usr/bin/python* /usr/bin/
RUN rm -rf /usr/local/lib/python3.10/dist-packages
COPY --from=builder /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.10/dist-packages
COPY --from=builder /usr/local/bin/vllm /usr/local/bin/vllm

#RUN ln -sf /usr/bin/python3.10 /usr/bin/python3

#COPY --from=builder /usr/local/bin/vllm-* /usr/local/bin/  # to catch all scripts
#COPY --from=builder /etc/* /etc/  # only if you know what you need

ENV PATH="/usr/local/bin:$PATH"

# optionally set entrypoint
ENTRYPOINT ["vllm"]

CMD ["--help"]